App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name="sign_up"),
    path('login/', views.login_page, name="login"),
    path('edit/', views.edit_profile, name="edit"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('user/<username>/', views.user, name="user"),
    path('follow/<username>/', views.follow, name="follow"),
    path('unfollow/<username>/', views.unfollow, name="unfollow"),
]

App_Posts/urls.py
from django.urls import path
from App_Posts import views
from .views import PostListAPIView, PostDetailAPIView, LikeListAPIView, LikeDetailAPIView


app_name = "App_Posts"

urlpatterns = [
    path("", views.home, name="home"),
    path("liked/<pk>/", views.liked, name="liked"),
    path("unliked/<pk>/", views.unliked, name="unliked"),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),

    path('posts/', PostListAPIView.as_view(), name='post-list'),
    path('posts/<int:pk>/', PostDetailAPIView.as_view(), name='post-detail'),
    path('likes/', LikeListAPIView.as_view(), name='like-list'),
    path('likes/<int:pk>/', LikeDetailAPIView.as_view(), name='like-detail'),
]

Event_Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Posts.urls')),
    path('', views.home, name='home')
]

# for adding images
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name="user_profile")  # make relation with when user is registered
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Your Email'})) #as not included in User auth class
    username = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Your Name'}))
    password1 = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    class Meta:
        model = User
        fields = ('email','username','password1','password2')

class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type':'date',}))
    class Meta:
        model = UserProfile
        exclude = ('user',)

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from App_Login.forms import CreateNewUser
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from App_Login.models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_Login.forms import EditProfile
from App_Posts.forms import PostForm

from App_Posts.forms import PostForm
from django.contrib.auth.models import User


# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)  # making relation with the model "user" one to one field
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'title': 'Signup Form Here', 'form': form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)  # store the post request in the data variable
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)  # matching with database
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Posts:home'))
    return render(request, 'App_login/login.html', context={'title': 'Login Page', 'form': form})


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)  # fetch the requested user
    form = EditProfile(instance=current_user)  # modified changes will be kept here for future login

    if request.method == "POST":
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/profile.html', context={'title': 'Edit Profile Page', 'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    form = PostForm()  # initiating the form by calling it in a variable

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_Login/user.html', context={'title': 'User Profile', 'form': form})


@login_required
def user(request, username):
    user_other = User.objects.get(username=username)  # matches the username of the <a> tag
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user == request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/user_other.html',
                  context={'user_other': user_other, 'already_followed': already_followed})


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)  # Follow button click who do follow so username
    follower_user = request.user  # Who will follow like others
    already_followed = Follow.objects.filter(follower=follower_user,
                                             following=following_user)  # get all name list form the database
    if not already_followed:
        followed_user = Follow(follower=follower_user,
                               following=following_user)  # follow na korle follow te click korle username ta add hobe
        followed_user.save()
    return HttpResponseRedirect(
        reverse('App_Login:user', kwargs={'username': username}))  # kwargs for passing parameter


@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)  # Follow button click who do follow so username
    follower_user = request.user  # Who will follow like others
    already_followed = Follow.objects.filter(follower=follower_user,
                                             following=following_user)  # get all name list form the database
    already_followed.delete()
    return HttpResponseRedirect(
        reverse('App_Login:user', kwargs={'username': username}))  # kwargs for passing parameter

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock %}
{% block css_block %}
<style>
    .sign_up{
        width:550px;
        border: 1px solid #ccc;
        padding: 40px
    }
    .login{
        width:550px;
        border: 1px solid #ccc;
        padding: 40px
    }
</style>
{% endblock %}
{% block body_block %}
<center>
    <div class="sign_up">
        <h3>Login Form</h3><br>
    <form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" style="width:100%" class="btn btn-info btn-sm">Login</button>
</form>
</div>
    <div class="login">
        <p>Don't Have Account? <a href="{% url 'App_Login:sign_up' %}">Signup</a> </p>
    </div>
</center>
{% endblock %}

templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock %}
{% block body_block %}
<form method="post" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock %}

{% block body_block %}
<form method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-info btn-sm">Signup</button>
</form>

{% endblock %}

templates/App_Login/user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock %}
{% block css_block %}
<style>
    .crop{
        width: 200px;
        height: 200px;
        overflow: hidden;
    }
    .crop img{
        width: 400px;
        height: 300px;
        margin: -85px 0 0 -110px;
    }
</style>
{% endblock %}

{% block body_block %}
<div class="row">

    <div class="col-sm-8">
        <h3>{{ user.username }}<a href="{% url 'App_Login:edit'%}" class="btn btn-light">Edit Profile</a></h3>
        <h4>{{ user.post.count }} Hosting Events &nbsp;&nbsp; {{user.follower.count}} Followers &nbsp;&nbsp; {{user.following.count}} Following</h4>

        <br>
        <h3>{{user.user_profile.full_name}}</h3>
        <h6>{{user.user_profile.description}}</h6>
    </div>
</div>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Post Photo
</button>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Post Photo</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data"> <!--#important for photo upload-->
            {{form.as_p}} <!--#as paragraph-->
            {% csrf_token %}
            <button type="submit" class="btn btn-info btn-sm">Post Photo</button>
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

<br><br>
<div class="row">
    {% for post in user.post.all %}
    <div class="crop">
     <a href="{% url 'App_Posts:post_detail' pk=post.pk %}">
                <img src="/media/{{post.image}}" alt="">
            </a>

    </div>
    {% endfor %}
</div>

{% endblock %}

templates/App_Login/user_other.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %} User Profile Page {% endblock %}

{% block css_block %}
<style>
    .crop{
        width: 200px;
        height: 200px;
        overflow: hidden;
    }
    .crop img{
        width: 400px;
        height: 300px;
        margin: -85px 0 0 -110px;
    }
</style>
{% endblock %}


{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user_other.user_profile.profile_pic %}
        <img src="/media/profile_pics/{{user_other.user_profile.profile_pic }}" width="220px" height="220px" class="rounded-circle">
        {% else %}
        <img src="/media/profile_pics/download.jpg" width="220px" height="220px" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>{{ user_other.username }} &nbsp;
        {% if not already_followed %}
            <a href="{% url 'App_Login:follow' user_other.username %}" class="btn btn-primary">Follow</a>
            {% else %}
            <a href="{% url 'App_Login:unfollow' user_other.username %}" class="btn btn-primary">Unfollow</a>
            {%endif%}
        </h3>
        <h4>{{ user_other.post.count }} Posts &nbsp;&nbsp; {{user_other.follower.count}} Followers &nbsp;&nbsp; {{user_other.following.count}} Following</h4>

        <br>
        <h3>{{user_other.user_profile.full_name}}</h3>
        <h6>{{user_other.user_profile.description}}</h6>
    </div>
</div>

<br><br>
<div class="row">
    {% for post in user_other.post.all %}
    <div class="crop">
    <img src="/media/{{post.image}}" alt="">
    </div>
    {% endfor %}
</div>

{% endblock %}