App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name="sign_up"),
    path('login/', views.login_page, name="login"),
    path('edit/', views.edit_profile, name="edit"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('user/<username>/', views.user, name="user"),
    path('follow/<username>/', views.follow, name="follow"),
    path('unfollow/<username>/', views.unfollow, name="unfollow"),
]

App_Posts/urls.py
from django.urls import path
from App_Posts import views
from .views import PostListAPIView, PostDetailAPIView, LikeListAPIView, LikeDetailAPIView


app_name = "App_Posts"

urlpatterns = [
    path("", views.home, name="home"),
    path("liked/<pk>/", views.liked, name="liked"),
    path("unliked/<pk>/", views.unliked, name="unliked"),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),

    path('posts/', PostListAPIView.as_view(), name='post-list'),
    path('posts/<int:pk>/', PostDetailAPIView.as_view(), name='post-detail'),
    path('likes/', LikeListAPIView.as_view(), name='like-list'),
    path('likes/<int:pk>/', LikeDetailAPIView.as_view(), name='like-detail'),
]

Event_Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Posts.urls')),
    path('', views.home, name='home')
]

# for adding images
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Posts/models.py
import win32timezone
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to="post_images")
    event_title = models.CharField(max_length=264, blank=True)
    date = models.DateTimeField()
    time = models.TimeField()
    location = models.CharField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)  # New field for storing the number of likes
    max_likes = models.IntegerField(default=1)

    class Meta:
        ordering = ['-upload_date']  # last post will be displayed first


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):  # to show in database and admin panel
        return '{}  : {}'.format(self.user, self.post)

App_Posts/forms.py
from django import forms
from App_Posts.models import Post  # calling Post class for their attribute form AppPost project model.py folder


class PostForm(forms.ModelForm):
    class Meta:  # used to call attributes from Post model with two field image and caption
        model = Post
        fields = ['image', 'event_title', 'date', 'time', 'location', 'max_likes']

        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

App_Posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from App_Posts.models import Post, Like
from App_Login.models import Follow
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, AllowAny
from .serializers import PostSerializer, LikeSerializer


# Create your views here.

@login_required
def home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts = Post.objects.filter(author__in=following_list.values_list('following'))
    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)

    if request.method == 'GET':
        search = request.GET.get('search', '')
        user_results = User.objects.filter(username__icontains=search)
        post_results = Post.objects.filter(Q(event_title__icontains=search) | Q(location__icontains=search))

    return render(request, 'App_Posts/home.html', {
        'title': 'Home Page',
        'search': search,
        'user_results': user_results,
        'post_results': post_results,
        'posts': posts,
        'liked_post_list': liked_post_list
    })


@login_required
def liked(request, pk):
    post = get_object_or_404(Post, pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user).exists()

    if not already_liked:
        liked_post = Like(post=post, user=request.user)
        liked_post.save()
        post.likes += 1  # Increment the likes count
        post.save()

    return HttpResponseRedirect(reverse('home'))


@login_required
def unliked(request, pk):
    post = get_object_or_404(Post, pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user).exists()

    if already_liked:
        Like.objects.filter(post=post, user=request.user).delete()
        post.likes -= 1  # Decrement the likes count
        post.save()

    return HttpResponseRedirect(reverse('home'))


@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    liked = post.pk in Like.objects.filter(user=request.user).values_list('post', flat=True)
    return render(request, 'App_Posts/post_detail.html', {'post': post, 'liked': liked})


class PostListAPIView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [AllowAny]


class PostDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [AllowAny]


class LikeListAPIView(generics.ListCreateAPIView):
    queryset = Like.objects.all()
    serializer_class = LikeSerializer
    permission_classes = [AllowAny]


class LikeDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Like.objects.all()
    serializer_class = LikeSerializer
    permission_classes = [AllowAny]

templates/App_Posts/home.html
{% extends 'navbar.html' %}
{% block title %} {{ title }}  {% endblock %}

{% block body_block %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">


{% if search %}

    {% for user in result %}
        <div>
            <div class="col-sm-2">
                {% if user.user_profile.profile_pic %}
                    <img src="/media/{{ user.user_profile.profile_pic }}" width="75px" height="75px" class="rounded-circle">
                {% else %}
                    <img src="/media/profile_pics/download.jpg" width="75px" height="75px" class="rounded-circle" > </a>
                {% endif %}
            </div>
            <div class="col-sm-10">
                <a href="{% url 'App_Login:user' user.username %}"> <h6>{{ user.username }}</h6> </a>
                <h6>{{ user.user_profile.full_name }}</h6>
            </div>
        </div>
    {% endfor %}

    {% for post in post_results %}
        <div>
            <h3><a href="{% url 'App_Posts:post_detail' pk=post.pk %}">{{ post.event_title }}</a></h3>
            <p>Post Location: {{ post.location }}</p>
            <!-- Add more details as needed -->
        </div>
    {% endfor %}

{% else %}
    <div class="row">
        <div class="col-sm-8">
            {% for post in posts %}
                <div style="border:1px solid #ddd;">
                    <div class="">
                        {% if post.author.user_profile.profile_pic %}
                            <img src="/media/{{ post.author.user_profile.profile_pic }}" width="50px" height="50px" class="rounded-circle">
                        {% else %}
                            <img src="/media/profile_pics/download.jpg" width="50px" height="50px" class="rounded-circle" > </a>
                        {% endif %}
                        <a href="{% url 'App_Login:user' post.author %}">{{post.author}}</a>
                    </div>
                    <br>
                    <img src="/media/{{post.image}}" width="100%">
                    <div style="padding:20px">
                        <h3><i class="fas fa-calendar"></i> {{post.event_title}}</h3>
    <h3><i class="fas fa-map-marker-alt"></i> {{post.location}}</h3>
    <h3><i class="far fa-clock"></i> {{post.time}}</h3>
    <h3><i class="far fa-calendar-alt"></i> {{post.date}}</h3>
    <h3><i class="fas fa-users"></i> {{post.max_likes}}</h3>
                        <p>Attendant: {{ post.likes }}</p>
                        {% if post.likes < post.max_likes %}
    {% if post.pk in liked_post_list %}
        <a href="{% url 'App_Posts:unliked' pk=post.pk %}"> <button class="btn btn-danger">Not Going</button></a>
    {% else %}
        <a href="{% url 'App_Posts:liked' pk=post.pk %}"> <button class="btn btn-success">Going</button></a>
    {% endif %}
{% else %}
    {% if post.pk in liked_post_list %}
        <a href="{% url 'App_Posts:unliked' pk=post.pk %}"> <button class="btn btn-danger">Not Going</button></a>
    {% else %}
        <button class="btn btn-success" disabled> Not Allowed</button>
    {% endif %}
{% endif %}

                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-4">
                    {% if user.user_profile.profile_pic %}
                        <img src="/media/{{ user.user_profile.profile_pic }}" width="75px" height="75px" class="rounded-circle">
                    {% else %}
                        <img src="/media/profile_pics/download.jpg" width="75px" height="75px" class="rounded-circle" > </a>
                    {% endif %}
                </div>
                <div class="col-sm-8">
                    <b>{{user.username}}</b><br>
                    <b>{{user.user_profile.fullname}}</b>
                </div>
            </div>
        </div>
    </div>

{% endif %}

{% endblock %}

templates/App_Posts/post_detail.html
<div style="border:1px solid #ddd;">
    <div class="">
        {% if post.author.user_profile.profile_pic %}
            <img src="/media/{{ post.author.user_profile.profile_pic }}" width="50px" height="50px" class="rounded-circle">
        {% else %}
            <img src="/media/profile_pics/download.jpg" width="50px" height="50px" class="rounded-circle">
        {% endif %}
        <a href="{% url 'App_Login:user' post.author %}">{{ post.author }}</a>
    </div>
    <br>
    <img src="/media/{{ post.image }}" width="100%">
    <div style="padding:20px">
        <h3>{{ post.event_title }}</h3>
        <h3>{{ post.location }}</h3>
        <h3>{{ post.time }}</h3>
        <h3>{{ post.date }}</h3>
        {% if liked %}
            <a href="{% url 'App_Posts:unliked' pk=post.pk %}"><i class="fa fa-heart" style="font-size:36px"></i></a>
        {% else %}
            <a href="{% url 'App_Posts:liked' pk=post.pk %}"><i class="fa fa-heart-o" style="font-size:36px"></i></a>
        {% endif %}
    </div>
</div>